- name: get key
  shell: cat /var/lib/jenkins/.ssh/id_rsa.pub
  register: key
  
- name: print key
  debug:
    msg: "{{key.stdout}}"
- name: Deploy public key
  digital_ocean: >
    state=present
    command=ssh
    name=my_new_key
    api_token="{{ api_key }}"
    ssh_pub_key="{{ my_pub_key }}"
  register: do_droplet
  
- name: whoami
  shell: whoami
  register: out
- name: debug
  debug:
    msg: "{{out.stdout}}"
     
- name: Create Digital Ocean droplet 512Mb/Ubuntu12.04 LTS/Amsterdam
  digital_ocean: >   
    state=present
    command=droplet
    name="{{ do_hostname }}"
    api_token="{{ api_key }}"
    size_id=1gb
    ssh_key_ids="{{ do_droplet.ssh_key.id }}"
    region_id=nyc1
    image_id=ubuntu-14-04-x64
    wait_timeout=600
  register: do_droplet

- debug: msg="ID is {{ do_droplet.droplet.id }}"
- debug: msg="IP is {{ do_droplet.droplet.ip_address }}"
    
- name: Add new droplet to inventory
  add_host: >
    name="{{ do_droplet.droplet.ip_address }}"
    groups=newdroplets
    ansible_ssh_user=root
    host_key_checking = False
    ansible_ssh_private_key_file=/var/lib/jenkins/.ssh/id_rsa
- name: Wait for VM to come up
  local_action: wait_for host="{{ do_droplet.droplet.ip_address }}" state=started
  async: no    
- name: ensure droplet exists
  digital_ocean: >
    state=present
    command=droplet
    api_token="{{ api_key }}"
    name="{{ do_hostname }}"
    unique_name=yes
    size_id=1gb
    region_id=nyc1
    image_id=ubuntu-14-04-x64
          
